# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Khauri/Desktop/HouseHaunters

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Khauri/Desktop/HouseHaunters/debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Khauri/Desktop/HouseHaunters/debug/CMakeFiles /mnt/c/Users/Khauri/Desktop/HouseHaunters/debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Khauri/Desktop/HouseHaunters/debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HH

# Build rule for target.
HH: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HH
.PHONY : HH

# fast build rule for target.
HH/fast:
	$(MAKE) -f CMakeFiles/HH.dir/build.make CMakeFiles/HH.dir/build
.PHONY : HH/fast

#=============================================================================
# Target rules for targets named HouseHaunters_core

# Build rule for target.
HouseHaunters_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HouseHaunters_core
.PHONY : HouseHaunters_core

# fast build rule for target.
HouseHaunters_core/fast:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/build
.PHONY : HouseHaunters_core/fast

bin/HH.o: bin/HH.cpp.o

.PHONY : bin/HH.o

# target to build an object file
bin/HH.cpp.o:
	$(MAKE) -f CMakeFiles/HH.dir/build.make CMakeFiles/HH.dir/bin/HH.cpp.o
.PHONY : bin/HH.cpp.o

bin/HH.i: bin/HH.cpp.i

.PHONY : bin/HH.i

# target to preprocess a source file
bin/HH.cpp.i:
	$(MAKE) -f CMakeFiles/HH.dir/build.make CMakeFiles/HH.dir/bin/HH.cpp.i
.PHONY : bin/HH.cpp.i

bin/HH.s: bin/HH.cpp.s

.PHONY : bin/HH.s

# target to generate assembly for a file
bin/HH.cpp.s:
	$(MAKE) -f CMakeFiles/HH.dir/build.make CMakeFiles/HH.dir/bin/HH.cpp.s
.PHONY : bin/HH.cpp.s

src/GameEngine.o: src/GameEngine.cpp.o

.PHONY : src/GameEngine.o

# target to build an object file
src/GameEngine.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameEngine.cpp.o
.PHONY : src/GameEngine.cpp.o

src/GameEngine.i: src/GameEngine.cpp.i

.PHONY : src/GameEngine.i

# target to preprocess a source file
src/GameEngine.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameEngine.cpp.i
.PHONY : src/GameEngine.cpp.i

src/GameEngine.s: src/GameEngine.cpp.s

.PHONY : src/GameEngine.s

# target to generate assembly for a file
src/GameEngine.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameEngine.cpp.s
.PHONY : src/GameEngine.cpp.s

src/GameObject.o: src/GameObject.cpp.o

.PHONY : src/GameObject.o

# target to build an object file
src/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameObject.cpp.o
.PHONY : src/GameObject.cpp.o

src/GameObject.i: src/GameObject.cpp.i

.PHONY : src/GameObject.i

# target to preprocess a source file
src/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameObject.cpp.i
.PHONY : src/GameObject.cpp.i

src/GameObject.s: src/GameObject.cpp.s

.PHONY : src/GameObject.s

# target to generate assembly for a file
src/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameObject.cpp.s
.PHONY : src/GameObject.cpp.s

src/GameScreen.o: src/GameScreen.cpp.o

.PHONY : src/GameScreen.o

# target to build an object file
src/GameScreen.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameScreen.cpp.o
.PHONY : src/GameScreen.cpp.o

src/GameScreen.i: src/GameScreen.cpp.i

.PHONY : src/GameScreen.i

# target to preprocess a source file
src/GameScreen.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameScreen.cpp.i
.PHONY : src/GameScreen.cpp.i

src/GameScreen.s: src/GameScreen.cpp.s

.PHONY : src/GameScreen.s

# target to generate assembly for a file
src/GameScreen.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameScreen.cpp.s
.PHONY : src/GameScreen.cpp.s

src/GameplayScreen.o: src/GameplayScreen.cpp.o

.PHONY : src/GameplayScreen.o

# target to build an object file
src/GameplayScreen.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameplayScreen.cpp.o
.PHONY : src/GameplayScreen.cpp.o

src/GameplayScreen.i: src/GameplayScreen.cpp.i

.PHONY : src/GameplayScreen.i

# target to preprocess a source file
src/GameplayScreen.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameplayScreen.cpp.i
.PHONY : src/GameplayScreen.cpp.i

src/GameplayScreen.s: src/GameplayScreen.cpp.s

.PHONY : src/GameplayScreen.s

# target to generate assembly for a file
src/GameplayScreen.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/GameplayScreen.cpp.s
.PHONY : src/GameplayScreen.cpp.s

src/HouseHaunters.o: src/HouseHaunters.cpp.o

.PHONY : src/HouseHaunters.o

# target to build an object file
src/HouseHaunters.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/HouseHaunters.cpp.o
.PHONY : src/HouseHaunters.cpp.o

src/HouseHaunters.i: src/HouseHaunters.cpp.i

.PHONY : src/HouseHaunters.i

# target to preprocess a source file
src/HouseHaunters.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/HouseHaunters.cpp.i
.PHONY : src/HouseHaunters.cpp.i

src/HouseHaunters.s: src/HouseHaunters.cpp.s

.PHONY : src/HouseHaunters.s

# target to generate assembly for a file
src/HouseHaunters.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/HouseHaunters.cpp.s
.PHONY : src/HouseHaunters.cpp.s

src/Interpolate.o: src/Interpolate.cpp.o

.PHONY : src/Interpolate.o

# target to build an object file
src/Interpolate.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Interpolate.cpp.o
.PHONY : src/Interpolate.cpp.o

src/Interpolate.i: src/Interpolate.cpp.i

.PHONY : src/Interpolate.i

# target to preprocess a source file
src/Interpolate.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Interpolate.cpp.i
.PHONY : src/Interpolate.cpp.i

src/Interpolate.s: src/Interpolate.cpp.s

.PHONY : src/Interpolate.s

# target to generate assembly for a file
src/Interpolate.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Interpolate.cpp.s
.PHONY : src/Interpolate.cpp.s

src/Joystick.o: src/Joystick.cpp.o

.PHONY : src/Joystick.o

# target to build an object file
src/Joystick.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Joystick.cpp.o
.PHONY : src/Joystick.cpp.o

src/Joystick.i: src/Joystick.cpp.i

.PHONY : src/Joystick.i

# target to preprocess a source file
src/Joystick.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Joystick.cpp.i
.PHONY : src/Joystick.cpp.i

src/Joystick.s: src/Joystick.cpp.s

.PHONY : src/Joystick.s

# target to generate assembly for a file
src/Joystick.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Joystick.cpp.s
.PHONY : src/Joystick.cpp.s

src/Random.o: src/Random.cpp.o

.PHONY : src/Random.o

# target to build an object file
src/Random.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Random.cpp.o
.PHONY : src/Random.cpp.o

src/Random.i: src/Random.cpp.i

.PHONY : src/Random.i

# target to preprocess a source file
src/Random.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Random.cpp.i
.PHONY : src/Random.cpp.i

src/Random.s: src/Random.cpp.s

.PHONY : src/Random.s

# target to generate assembly for a file
src/Random.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/Random.cpp.s
.PHONY : src/Random.cpp.s

src/SpriteAnimation.o: src/SpriteAnimation.cpp.o

.PHONY : src/SpriteAnimation.o

# target to build an object file
src/SpriteAnimation.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/SpriteAnimation.cpp.o
.PHONY : src/SpriteAnimation.cpp.o

src/SpriteAnimation.i: src/SpriteAnimation.cpp.i

.PHONY : src/SpriteAnimation.i

# target to preprocess a source file
src/SpriteAnimation.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/SpriteAnimation.cpp.i
.PHONY : src/SpriteAnimation.cpp.i

src/SpriteAnimation.s: src/SpriteAnimation.cpp.s

.PHONY : src/SpriteAnimation.s

# target to generate assembly for a file
src/SpriteAnimation.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/SpriteAnimation.cpp.s
.PHONY : src/SpriteAnimation.cpp.s

src/rando.o: src/rando.cpp.o

.PHONY : src/rando.o

# target to build an object file
src/rando.cpp.o:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/rando.cpp.o
.PHONY : src/rando.cpp.o

src/rando.i: src/rando.cpp.i

.PHONY : src/rando.i

# target to preprocess a source file
src/rando.cpp.i:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/rando.cpp.i
.PHONY : src/rando.cpp.i

src/rando.s: src/rando.cpp.s

.PHONY : src/rando.s

# target to generate assembly for a file
src/rando.cpp.s:
	$(MAKE) -f CMakeFiles/HouseHaunters_core.dir/build.make CMakeFiles/HouseHaunters_core.dir/src/rando.cpp.s
.PHONY : src/rando.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... HH"
	@echo "... HouseHaunters_core"
	@echo "... bin/HH.o"
	@echo "... bin/HH.i"
	@echo "... bin/HH.s"
	@echo "... src/GameEngine.o"
	@echo "... src/GameEngine.i"
	@echo "... src/GameEngine.s"
	@echo "... src/GameObject.o"
	@echo "... src/GameObject.i"
	@echo "... src/GameObject.s"
	@echo "... src/GameScreen.o"
	@echo "... src/GameScreen.i"
	@echo "... src/GameScreen.s"
	@echo "... src/GameplayScreen.o"
	@echo "... src/GameplayScreen.i"
	@echo "... src/GameplayScreen.s"
	@echo "... src/HouseHaunters.o"
	@echo "... src/HouseHaunters.i"
	@echo "... src/HouseHaunters.s"
	@echo "... src/Interpolate.o"
	@echo "... src/Interpolate.i"
	@echo "... src/Interpolate.s"
	@echo "... src/Joystick.o"
	@echo "... src/Joystick.i"
	@echo "... src/Joystick.s"
	@echo "... src/Random.o"
	@echo "... src/Random.i"
	@echo "... src/Random.s"
	@echo "... src/SpriteAnimation.o"
	@echo "... src/SpriteAnimation.i"
	@echo "... src/SpriteAnimation.s"
	@echo "... src/rando.o"
	@echo "... src/rando.i"
	@echo "... src/rando.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

